name: CI

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: pnpm

      - name: Audit dependencies
        run: pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Storefront changed in last commit?
        id: changed-storefront
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: storefront
          from: HEAD^1

      - name: Validate Action Output
        if: steps.changed-storefront.outputs.changed == 'true'
        run: echo 'storefront changed!'

      - name: Server changed in last commit?
        id: changed-server
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: server
          from: HEAD^1

      - name: Deploy Server
        if: steps.changed-server.outputs.changed == 'true'
        uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: "server"
          detach: true
